"iam": "platform settings"
# site
"iam.organization": "Organization"
"iam.menu-management": "Menu Setting"
"iam.role-label": "Role Label"
"iam.role": "Role"
"iam.member-role-global": "Role Assignment"
"iam.root-user": "Root User Setting"
"iam.dashboard-management": "Dashboard Setting"

"microservice": "Microservice"
"microservice.micro": "Microservice"
"microservice.route-management": "Route Management"
"microservice.config-management": "Config Management"
"microservice.instance-management": "Instance Management"

"api": "API Manage"
"api.api-test": "API Test"

"global-transaction": "Global Transaction"
"global-transaction.saga": "Saga"
"global-transaction.saga-instance": "Saga Instance"

"msg-center": "Message Center"
"msg-center.send-setting": "Send Setting"
"msg-center.mail-template": "Mail Template"
"msg-center.mail-setting": "Mail Config"
"msg-center.msg-record": "Message Record"

"rentsetting": "Organization settings"
# organization
"rentsetting.project": "Project"
"rentsetting.user": "User"
"rentsetting.member-role-organization": "Role Assignment"
"rentsetting.client": "Client"
"rentsetting.ldap": "LDAP"
"rentsetting.password-policy": "Password Policy"

"msg-center-organization": "Message Center"
"msg-center-organization.send-setting-organization": "Send Setting"
"msg-center-organization.mail-template-organization": "Mail Template"
"msg-center-organization.msg-record-organization": "Message Record"

"prosetting": "Project Manage"
# project
"prosetting.proManage": "Project Manage"
"prosetting.member-role-project": "Role Assignment"

"usercenter": "Profile"
# user
"usercenter.user-info": "User Information Maintenance"
"usercenter.password": "Password Modification"
"usercenter.organization-info": "Organization Information"
"usercenter.project-info": "Project Information"

