image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cifront:0.5.0

stages:
  - node_build
  - docker_build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

node_build:
  stage: node_build
  script:
    - node_module iam
    - node_build build
    - cp -r dist /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/dist
  only:
    - /^release-.*$/
    - /^hotfix-.*$/
    - develop
    - tags

node_build_dev:
  stage: node_build
  script:
    - node_module iam
    - node_build build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  only:
    - /^feature-.*$/

docker_build:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0
  stage: docker_build
  script:
    - docker_build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - chart_build
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

.auto_devops: &auto_devops |
    curl -o .auto_devops.sh \
        "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
    if [ $? -ne 0 ];then
      cat .auto_devops.sh
      exit 1
    fi
    source .auto_devops.sh    
    function node_module(){
        cd ${1} && npm install -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ && cd ..
        mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
        python ./${1}/node_modules/choerodon-front-boot/structure/configAuto.py ${1}
        cp -r config.yml /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/
        cd ${1}
    }

    function node_build(){
        chmod -R 777 node_modules
        npm run ${1:-"build"}
        find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
    }

    function docker_build(){
        cp -r /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/* ${1:-"."}
        docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"."}
        docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    }

before_script:
  - *auto_devops
