default: &default
  docker:
  - image: choerodon/cifront:0.5.0

version: 2
jobs:
  node_build:
    <<: *default
    working_directory: ~/repo
    environment:
      CI_PROJECT_PATH: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run: |
            export CI_COMMIT_TAG=$CIRCLE_TAG
            cd iam && npm install -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ && cd ..
            python ./iam/node_modules/choerodon-front-boot/structure/configAuto.py iam
            cd iam
            chmod -R 777 node_modules
            npm run build
            find dist -name '*.js' | xargs sed -i "s/localhost:version/${CI_COMMIT_TAG}/g"
      - persist_to_workspace:
          root: .
          paths:
            - config.yml
            - iam/dist
            - iam/node_modules/choerodon-front-boot/structure
  docker_build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          mv iam/dist ./dist
          cp -r iam/node_modules/choerodon-front-boot/structure structure
          sed -i "s/registry.cn-hangzhou.aliyuncs.com\/choerodon-tools/choerodon/g" Dockerfile
          export CI_COMMIT_TAG=$CIRCLE_TAG
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build --pull -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG} .
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG}
  helm_chart_build:
    docker:
    - image: choerodon/cibase:0.5.0
    steps:
      - checkout
      - run: |
          export CI_COMMIT_TAG=$(GetVersion)
          CHART_PATH=`find . -name Chart.yaml`
          yq w -i ${CHART_PATH%/*}/values.yaml image.repository ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}
          yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CI_COMMIT_TAG}
          helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
          helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CI_COMMIT_TAG} choerodon
workflows:
  version: 2
  release:
    jobs:
      - node_build:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - docker_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - helm_chart_build:
          context: org-global
          requires:
          - node_build
          - docker_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
  daily:
    jobs:
      - node_build:
          context: org-global
          filters:
            branches:
              only:
               - master
