"iam":
  icon: IAM
  sort: 1
  site:
    - "organization":
        icon: manage_organization
        Routes: /iam/organization
        sort: 1
        permission:
          - 'iam-service.organization.list'
          - 'organization-service.organization.create'
          - 'iam-service.organization.check'
          - 'iam-service.organization.query'
          - 'iam-service.organization.update'
          - 'iam-service.organization.disableOrganization'
          - 'iam-service.organization.enableOrganization'
    - "menu-management":
        icon: view_list
        Routes: /iam/menu-setting
        sort: 2
        permission:
          - 'iam-service.menu.create'
          - 'iam-service.menu.saveListTree'
          - 'iam-service.menu.query'
          - 'iam-service.menu.update'
          - 'iam-service.menu.delete'
    - "role-label":
        icon: role_tag
        Routes: /iam/role-label
        sort: 3
        permission:
          - 'iam-service.label.listByType'
    - "role":
        icon: assignment_ind
        Routes: /iam/role
        sort: 4
        permission:
          - 'iam-service.role.create'
          - 'iam-service.role.createBaseOnRoles'
          - 'iam-service.role.check'
          - 'iam-service.role.list'
          - 'iam-service.role-member.listRolesWithUserCountOnSiteLevel'
          - 'iam-service.role.queryWithPermissionsAndLabels'
          - 'iam-service.role.update'
          - 'iam-service.role.disableRole'
          - 'iam-service.role.enableRole'
          - 'iam-service.role-member.pagingQueryUsersByRoleIdOnSiteLevel'
    - "member-role-global":
        icon: person_add
        Routes: /iam/member-role
        sort: 5
        permission:
          - 'iam-service.role-member.createOrUpdateOnSiteLevel'
          - 'iam-service.role-member.deleteOnSiteLevel'
          - 'iam-service.role-member.pagingQueryUsersByRoleIdOnSiteLevel'
          - 'iam-service.role-member.listRolesWithUserCountOnSiteLevel'
          - 'iam-service.role-member.pagingQueryUsersWithSiteLevelRoles'
    - "root-user":
        icon: root
        Routes: /iam/root-user
        sort: 6
        permission:
          - 'iam-service.user.pagingQueryAdminUsers'
          - 'iam-service.user.addDefaultUsers'
          - 'iam-service.user.deleteDefaultUser'
    - "dashboard-management":
        icon: donut_small
        Routes: /iam/dashboard-setting
        sort: 7
        permission:
          - 'iam-service.dashboard.list'
          - 'iam-service.dashboard.query'
          - 'iam-service.dashboard.update'

# 微服务管理
"microservice":
  icon: micro
  sort: 2
  site:
    - "micro":
        icon: microservice
        Routes: /iam/microservice
        sort: 1
        permission:
          - 'manager-service.service.pageManager'
    - "instance-management":
        icon: instance_outline
        Routes: /iam/instance
        sort: 2
        permission:
          - 'manager-service.instance.list'
          - 'manager-service.instance.query'
    - "config-management":
        icon: settings_input_composite
        Routes: /iam/configuration
        sort: 3
        permission:
          - 'manager-service.config.query'
          - 'manager-service.config.create'
          - 'manager-service.config.delete'
          - 'manager-service.config.queryYaml'
          - 'manager-service.config.updateConfig'
          - 'manager-service.config.updateConfigDefault'
    - "route-management":
        icon: routeroutline
        Routes: /iam/route
        sort: 4
        permission:
          - 'manager-service.route.list'
          - 'manager-service.route.create'
          - 'manager-service.route.update'
          - 'manager-service.route.delete'

# api管理
"api":
  icon: API
  sort: 3
  site:
    - "api-test":
        icon: APItest
        Routes: /iam/api-test
        sort: 1
        permission:
        - 'manager-service.service.pageManager'

# 消息中心
"msg-center":
  icon: center
  sort: 4
  site:
    - "send-setting":
        icon: mail_set
        Routes: /iam/send-setting
        sort: 1
        permission:
        - 'notify-service.send-setting-site.pageSite'
    - "mail-template":
        icon: application_model
        Routes: /iam/mail-template
        sort: 2
        permission:
        - 'notify-service.email-template-site.pageSite'
        - 'notify-service.email-template-site.create'
        - 'notify-service.email-template-site.update'
        - 'notify-service.email-template-site.query'
        - 'notify-service.send-setting-site.listNames'
    - "mail-setting":
        icon: contact_mail
        Routes: /iam/mail-setting
        sort: 3
        permission:
        - 'notify-service.config.selectEmail'
        - 'notify-service.config.testEmailConnect'
        - 'notify-service.config.updateEmail'
    - "msg-record":
        icon: speaker_notes
        Routes: /iam/msg-record
        sort: 4
        permission:
        - 'notify-service.message-record-site.pageEmail'

# 任务调度
"task-dispatch":
  icon: work_log
  sort: 5
  site:
    - "task-detail":
        icon: work_log
        Routes: /iam/task-detail
        sort: 1
        permission:
          - 'notify-service.send-setting-site.pageSite'
    - "execution-record":
        icon: work_log
        Routes: /iam/execution-record
        sort: 2
        permission:
          - 'notify-service.send-setting-site.pageSite'

# 事务管理
"global-transaction":
  icon: developer_board
  sort: 6
  site:
    - "saga":
        icon: saga_define
        Routes: /iam/saga
        sort: 1
        permission:
          - 'asgard-service.saga.pagingQuery'
          - 'asgard-service.saga.query'
    - "saga-instance":
        icon: instance_outline
        Routes: /iam/saga-instance
        sort: 2
        permission:
          - 'asgard-service.saga-instance.pagingQuery'
          - 'asgard-service.saga-instance.query'

# 组织设置
"rentsetting":
  icon: IAM
  sort: 2
  organization:
    - "project":
        icon: manage_project
        Routes: /iam/project
        sort: 1
        permission:
          - 'iam-service.organization-project.list'
          - 'iam-service.organization-project.create'
          - 'iam-service.organization-project.update'
          - 'iam-service.organization-project.check'
          - 'iam-service.organization-project.enableProject'
          - 'iam-service.organization-project.disableProject'
    - "user":
        icon: manage_person
        Routes: /iam/user
        sort: 2
        permission:
          - 'iam-service.organization-user.create'
          - 'iam-service.organization-user.list'
          - 'iam-service.organization-user.query'
          - 'iam-service.organization-user.update'
          - 'iam-service.organization-user.delete'
          - 'iam-service.organization-user.disableUser'
          - 'iam-service.organization-user.enableUser'
          - 'iam-service.organization-user.unlock'
    - "member-role-organization":
        icon: person_add
        Routes: /iam/member-role
        sort: 3
        permission:
          - 'iam-service.role-member.createOrUpdateOnOrganizationLevel'
          - 'iam-service.role-member.deleteOnOrganizationLevel'
          - 'iam-service.role-member.listRolesWithUserCountOnOrganizationLevel'
          - 'iam-service.role-member.pagingQueryUsersByRoleIdOnOrganizationLevel'
          - 'iam-service.role-member.pagingQueryUsersWithOrganizationLevelRoles'
    - "client":
        icon: laptop_mac
        Routes: /iam/client
        sort: 4
        permission:
          - 'iam-service.client.check'
          - 'iam-service.client.create'
          - 'iam-service.client.delete'
          - 'iam-service.client.list'
          - 'iam-service.client.query'
          - 'iam-service.client.queryByName'
          - 'iam-service.client.update'
    - "ldap":
        icon: device_hub
        Routes: /iam/ldap
        sort: 5
        permission:
          - 'iam-service.ldap.create'
          - 'iam-service.ldap.query'
          - 'iam-service.ldap.queryByOrgId'
          - 'iam-service.ldap.syncUsers'
          - 'iam-service.ldap.testConnect'
          - 'iam-service.ldap.update'
    - "password-policy":
        icon: password
        Routes: /iam/password-policy
        sort: 6
        permission:
          - 'iam-service.password-policy.create'
          - 'iam-service.password-policy.queryByOrganizationId'
          - 'iam-service.password-policy.update'
    - "mail-template-organization":
        icon: application_model
        Routes: /iam/mail-template
        sort: 7
        delete: true
        permission:
          - 'notify-service.email-template-org.pageOrganization'
          - 'notify-service.email-template-org.create'
          - 'notify-service.email-template-org.update'
          - 'notify-service.email-template-org.delete'
          - 'notify-service.email-template-org.query'
          - 'notify-service.send-setting-org.listNames'

# 组织层消息中心
"msg-center-organization":
  icon: center
  sort: 3
  organization:
    - "send-setting-organization":
        icon: mail_set
        Routes: /iam/send-setting
        sort: 1
        permission:
          - 'notify-service.send-setting-org.pageOrganization'
    - "mail-template-organization":
        icon: application_model
        Routes: /iam/mail-template
        sort: 2
        permission:
          - 'notify-service.email-template-org.pageOrganization'
          - 'notify-service.email-template-org.create'
          - 'notify-service.email-template-org.update'
          - 'notify-service.email-template-org.delete'
          - 'notify-service.email-template-org.query'
          - 'notify-service.send-setting-org.listNames'
    - "msg-record-organization":
        icon: speaker_notes
        Routes: /iam/msg-record
        sort: 3
        permission:
          - 'notify-service.message-record-org.pageEmail'

# 项目设置
"prosetting":
  icon: IAM
  sort: 6
  project:
    - "member-role-project":
        icon: person_add
        Routes: /iam/member-role
        sort: 1
        permission:
          - 'iam-service.role-member.createOrUpdateOnSiteLevel'
          - 'iam-service.role-member.deleteOnProjectLevel'
          - 'iam-service.role-member.listRolesWithUserCountOnProjectLevel'
          - 'iam-service.role-member.pagingQueryUsersByRoleIdOnProjectLevel'
          - 'iam-service.role-member.pagingQueryUsersWithProjectLevelRoles'
    - "proManage":
        icon: settings_applications
        Routes: /iam/project-setting
        sort: 2
        permission:
          - 'iam-service.project.disableProject'
          - 'iam-service.project.query'
          - 'iam-service.project.update'

# 个人中心
"usercenter":
  icon: accessibility
  sort: 1
  user:
    - "user-info":
        icon: person
        Routes: /iam/user-info
        sort: 1
        permission:
          - 'iam-service.user.queryInfo'
          - 'iam-service.user.updateInfo'
          - 'iam-service.user.uploadPhoto'
          - 'iam-service.user.querySelf'
    - "password":
        icon: vpn_key
        Routes: /iam/password
        sort: 2
        permission:
          - 'iam-service.user.selfUpdatePassword'
    - "organization-info":
        icon: domain
        Routes: /iam/organization-info
        sort: 3
        permission:
          - 'iam-service.user.listOrganizationAndRoleById'
    - "project-info":
        icon: project
        Routes: /iam/project-info
        sort: 4
        permission:
          - 'iam-service.user.listProjectAndRoleById'
